### ISSUE TITLE
Searchable online documentation

### ISSUE THREAD

**Issue by drphilmarshall** [LSST-nonproject/sims_maf_contrib#2]
We talked about this in Phoenix - the idea was to fix up the docstrings in the contributed files so that they compile into some nice set of online documentation. Alex Kim suggested "readthedocs", there's also sphinx and doxygen that we could use to make pages served on the gh-pages of this repo. Implementing this early might help us with the organisation of the contributed code.

**Comment by rhiannonlynne** [comment]
We're moving towards numpy style docstrings, to be used with sphinx and readTheDocs in core sims_maf.
We should do so in sims_maf_contrib as well! 
We do not have a 'live' read the docs version of the sims_maf documentation (yet) but if you clone the repo, then:
> cd doc
make html
open build/html/index.html

Note that on el capitan, 'make' is by default in /usr/bin -- you will not be able to actually build the documentation, because it won't be able to find the libraries LSST adds to DYLD_LIBRARY_PATH. 
A quick and dirty way around this is to copy /usr/bin/make to somewhere else and run it from there. You probably don't want to do this as a normal procedure, but it'll work for now.

**Comment by rhiannonlynne** [comment]
We are working on documentation, but some is available at 
https://sims-maf.lsst.io/
