### ISSUE TITLE
Tutorial histogram issues

### ISSUE THREAD

**Issue by MeganNewsome** [LSST-nonproject/sims_maf_contrib#49]
Not sure if anyone else is getting these. I've been running a lot of the tutorials within these notebooks, and first brushed off this issue, but now am starting to question it. The "Introduction Notebook" does not actually plot anything for certain histograms, such as the one for "airmass vs area." It is just a blank graph with a y-axis going from 0.000 to 0.001. My colleague and I noticed this when we were running the TransientAsciiMetric tutorial from science/transients, as the graphs would have y-axes ranging from 0.000 to as high as 0.215 (still showing nothing on the plot) if we put the healpix nside down to 4, but keeping it at 16 as the tutorial has it makes the y-axis go only from 0.000 to 0.013. It only happens with histogram plots in which the y-axis is "Area (1000s of square degrees)" but I'm not sure why these plots aren't showing up as the notebooks suggest they should. Is there something in the program for the metricBundle that filters down to these plots which I need to change? Thanks for any help and I'm happy to explain more if needed.

![image](https://user-images.githubusercontent.com/29585404/27455648-8da29ecc-578d-11e7-9b5a-6b04981f596d.png)
![image](https://user-images.githubusercontent.com/29585404/27455655-93248c34-578d-11e7-91a5-2739f0fe7cf7.png)

**Comment by rhiannonlynne** [comment]
Ah, I'm really sorry about that. It's a bug in MAF, where we have not set the histogram axes correctly.  I didn't think this had been in effect when we made the current -t sims tag, but apparently it is. We were debating today whether or not to make a new tag .. seems like this means we should! I will double-check that everything should work with the current master and then we can do the upgrade. 

In the meantime, if you don't want to wait for me to do that (it shouldn't be long, but I am coming up on vacation which might slow things down a bit) -- you can use the 'master' version from the git repo (I believe this is fixed there). 

To do that:

- decide where you'd like to locate a directory that will contain the MAF source code (I suggest making a 'lsstRepos' directory somewhere near your lsst stack directory, for clarity. let's call this directory $lsstRepos for now). 
- cd $lsstRepos
- git clone https://github.com/lsst/sims_maf.git  (this clones the git repo, and will make a directory sims_maf)
- cd sims_maf
- source loadLSST.csh (from the lsst stack installation)
- setup -r .
- scons  (this will 'build' the package, and run the unit tests)
After scons finishes, then
- eups declare sims_maf git -t $USER -r .

Now, anytime you want to use this version of sims_maf (the git clone version), you can 
- setup sims_maf -t $USER -t sims

and you will be ready to go with the git version instead of the version installed by eups distrib install.
(note that you can do this with any LSST package).

**Comment by MeganNewsome** [comment]
Thanks so much! I'm just glad to hear that at least it was something that was known about. Is this package still going to work down the road as updates and changes come out? Would I just update it as I would my current sims_maf?

**Comment by rhiannonlynne** [comment]
sims_maf has become "rubin_sim" and is much more simply conda installable.
